import { TaskPreset } from "./types";

export const defaultPresets: TaskPreset[] = [
  // === PARENTING (no time — just tallies) ===
  {
    id: "cook-breakfast",
    name: "Cook breakfast",
    category: "parenting",
    icon: "🍳",
  },
  {
    id: "cook-lunch",
    name: "Make lunch",
    category: "parenting",
    icon: "🥪",
  },
  {
    id: "cook-dinner",
    name: "Cook dinner",
    category: "parenting",
    icon: "🍲",
  },
  {
    id: "bathe-child",
    name: "Bathe child",
    category: "parenting",
    icon: "🛁",
  },
  {
    id: "brush-teeth",
    name: "Brush teeth",
    category: "parenting",
    icon: "🪥",
  },
  {
    id: "hair-care",
    name: "Hair — brush & braid",
    category: "parenting",
    icon: "💇",
  },
  {
    id: "pajamas",
    name: "Pajamas & getting ready for bed",
    category: "parenting",
    icon: "👕",
  },
  {
    id: "bedtime-stories",
    name: "Bedtime stories",
    category: "parenting",
    icon: "📖",
  },
  {
    id: "co-sleep",
    name: "Co-sleep / bedtime",
    category: "parenting",
    icon: "🌙",
  },
  {
    id: "play-together",
    name: "Play with child",
    category: "parenting",
    icon: "🧸",
  },
  {
    id: "school-dropoff",
    name: "School drop-off",
    category: "parenting",
    icon: "🚗",
  },
  {
    id: "school-pickup",
    name: "School pick-up",
    category: "parenting",
    icon: "🏫",
  },
  {
    id: "sick-care",
    name: "Sick care",
    category: "parenting",
    icon: "🤒",
  },
  {
    id: "child-laundry",
    name: "Child's laundry",
    category: "parenting",
    icon: "👶",
  },
  {
    id: "tidy-after-child",
    name: "Clean up after child's activity",
    category: "parenting",
    icon: "🧹",
  },

  // === SPOUSE-TIER ===
  {
    id: "mow-lawn",
    name: "Mow the lawn",
    category: "spouse",
    defaultMinutes: 120,
    dollarValue: 200,
    icon: "🌿",
  },
  {
    id: "yard-work",
    name: "Yard work",
    category: "spouse",
    defaultMinutes: 60,
    dollarValue: 75,
    icon: "🌳",
  },
  {
    id: "house-maintenance",
    name: "House maintenance",
    category: "spouse",
    defaultMinutes: 180,
    dollarValue: 300,
    icon: "🏠",
  },
  {
    id: "dishes",
    name: "Dishes",
    category: "spouse",
    defaultMinutes: 20,
    dollarValue: 15,
    icon: "🍽️",
  },
  {
    id: "household-laundry",
    name: "Household laundry",
    category: "spouse",
    defaultMinutes: 30,
    dollarValue: 20,
    icon: "🧺",
  },
  {
    id: "vacuum",
    name: "Vacuuming",
    category: "spouse",
    defaultMinutes: 25,
    dollarValue: 25,
    icon: "🧹",
  },
  {
    id: "tidy-house",
    name: "Tidy the house",
    category: "spouse",
    defaultMinutes: 30,
    dollarValue: 30,
    icon: "✨",
  },
  {
    id: "trash-out",
    name: "Take the trash out",
    category: "spouse",
    defaultMinutes: 10,
    dollarValue: 10,
    icon: "🗑️",
  },
  {
    id: "trash-curb",
    name: "Trash to the curb",
    category: "spouse",
    defaultMinutes: 10,
    dollarValue: 10,
    icon: "🚛",
  },
  {
    id: "compost",
    name: "Compost out",
    category: "spouse",
    defaultMinutes: 10,
    dollarValue: 10,
    icon: "🌱",
  },
  {
    id: "cat-litter",
    name: "Clean the cat litter",
    category: "spouse",
    defaultMinutes: 10,
    dollarValue: 10,
    icon: "🐱",
  },
  {
    id: "cat-water",
    name: "Change cat water",
    category: "spouse",
    defaultMinutes: 5,
    dollarValue: 5,
    icon: "💧",
  },
  {
    id: "water-plants",
    name: "Water the plants",
    category: "spouse",
    defaultMinutes: 15,
    dollarValue: 10,
    icon: "🪴",
  },
  {
    id: "groceries",
    name: "Grocery run",
    category: "spouse",
    defaultMinutes: 60,
    dollarValue: 50,
    icon: "🛒",
  },
  {
    id: "clean-kitchen",
    name: "Clean the kitchen",
    category: "spouse",
    defaultMinutes: 25,
    dollarValue: 25,
    icon: "🍳",
  },
  {
    id: "cross-purpose-cleanup",
    name: "Clean up other parent's mess",
    category: "spouse",
    defaultMinutes: 15,
    dollarValue: 15,
    icon: "🔄",
  },
];
